### ISSUE TITLE
4.3 Bard Updates

### ISSUE THREAD

**Issue by ghost** [parulina/bardmacroplayer#10] opened 2018-04-23 23:46 UTC
Do you plan to support the changes they make in 4.3?
I'm not sure if this would require you to change anything on your end, but you will be able to hold down notes in 4.3.

Does MIDI input and .txt files already support this, or will you have to do something?

**Comment by Decajack** [comment] 2018-04-24 21:27
I'm interested in this too, also, do yo plan to upgrade the macroplayer so it can play the +1 Half Step and the - 1 Half Step? Thanks for your work!!! :D

**Comment by pixaline** [comment] 2018-04-28 02:45
Making notes able to be held down should be fairly simple to implement. However i stopped playing the game so i would ask you to test my development builds for me. (or level up my bard alt for me if you want, hehehe)

Regarding half step, that is already supported. Unless i'm misunderstanding you.

**Comment by Decajack** [comment] 2018-04-28 02:53
Awsome!!! I'll gladly test your development builds, holding down the notes is supposed to be added on Patch 4.3.
About the half step issue,either the macro player doesn't need to use it or it's too quick for me to notice(I'm playing  songs with multiple notes).If you have a song that uses half step, i could confirm it.
Anways, thanks for the reply, i'll keep you updated!

**Comment by pixaline** [comment] 2018-04-28 03:21
If you have custom keybinds for half notes then there may be a problem caused by a bug. I've already fixed it in the source files but haven't published it as an exe. I've been thinking of releasing it now and make an announcement. You can get it here for the time being: [here](https://github.com/parulina/bardmacroplayer/files/1901693/BardMacroPlayer-1.2fixfix.zip).

**Comment by Decajack** [comment] 2018-04-28 03:28
Yup! There you go, i have custom keybinds for the half step.That's the problem then.
I'll try the fix tomorrow and keep you updated,thanks again, cheers!!!

**Comment by Decajack** [comment] 2018-05-13 21:38
Allright after seeing the last Live Letter, i got a chance to see the new enhanced Performance UI.
It's confirmed that they're going to add new wind instruments + holding keys + more Octaves, heres a pic of it: https://pbs.twimg.com/media/Dc6nDKFU0AAQkMB.jpg release is on the 22nd of this month!

**Comment by pixaline** [comment] 2018-05-14 19:18
Very interesting. I will need to level up my bard alt and make the changes once the patch goes live. For now I think I will release the new version to tide people over.

**Comment by Decajack** [comment] 2018-05-19 14:44
Excelent job the 1.3 update!!! Works wonderfully!. By the way parulina,i don't really know where to wirte suggestions, so i'll use this threat now that it's open.
The suggestion is to add FOLDERS and SUBFOLDERS for the songs,to make it more organized(or make albums), i have like 50+ songs and while the macroplayer does wonders, it's a little pain in the ass to search for the song i want to play.Here is an example:

Final Fantasy XIV
             -Limsa Lominsa Songs
             -La Noscea Songs
             -Trials Songs
Something like this, if this feature could be added in the future it would be fantastic.Keep up the good work! cheers!

**Comment by pixaline** [comment] 2018-05-19 15:00
Make a new issue with the big green button in the top right. Why do people ignore it? Please use it.
Folders should be doable. But let's continue it in a new thread.
Closing.

**Closed as completed by pixaline** 2018-05-19 15:00 UTC
