### ISSUE TITLE
Notes go missing if too many keybind files are detected.

### ISSUE THREAD

**Issue by Nerdorable** [parulina/bardmacroplayer#5] opened 2018-03-08 10:21 UTC
Today I created a couple of alt characters on my server and noticed afterwards that my songs were missing lots of notes. The program usually gives me an error about too many keybinds being detected, so I went and deleted four out of the seven folders I had under "Documents\My Games\FINAL FANTASY XIV". That seems to have fixed the problem, but I just thought I would post it as a known bug.

**Comment by pixaline** [comment] 2018-03-12 18:12
The problem is because the program tries to guess which keybind file to load when there's multiple ones. A solution would be to offer a way to switch keybinds manually. I might add a switcher in the Parsed keys window.

**Comment by Nerdorable** [comment] 2018-03-29 07:55
I now have a new issue related to this. This time when the program detected multiple keybind files and I deleted the excess character folders, restarting, it did not attempt to detect keybindings again. I tried restarting the program, XIV, and even my PC. Now the program is stuck this way and missing notes with no way for me to reset it. I even looked in AppData/Roaming to see if there was anything there I could delete relating to this program. Any idea how I could fix this?

**Comment by pixaline** [comment] 2018-03-30 02:47
Sorry for being inactive, been really busy with some of my other projects.
If keybind files are missing, you should go in to the settings in FFXIV (and maybe change a key and hit apply) and it should auto regenerate keybind files that the program can use, as a temporary fix. The error you see isn't actually a program error, it's more of a notification. I'm planning to change this.
I will need to create an option to switch between available keybinds, as it seems that many people are experiencing the same issues. I'll try and fix it this weekend.

**Comment by pixaline** [comment] 2018-04-02 13:34
[BardMacroPlayer-1.2fix.zip](https://github.com/parulina/bardmacroplayer/files/1868177/BardMacroPlayer-1.2fix.zip)
Could you try this build and see if it works? I've added a switch in the key config to be able to select different keybind files. I checked the code and realized i made a subtle typo causing random keybind files to be loaded. This should fix all keybind loading issues.

**Comment by Nerdorable** [comment] 2018-04-12 00:56
Thank you for getting a fix out so quickly! I've tested it with a variety of character folders/keybind files (up to ten) and it's had no issues detecting them. I think you've fixed it!

I'm really happy to see that you added the Speed Shift slider! There are some bugs I've discovered with it though. I will post those in a new Issue thread.

**Comment by pixaline** [comment] 2018-04-12 07:08
Cool, closing.

**Closed as completed by pixaline** 2018-04-12 07:08 UTC
